site_name: Ragr3n
site_url: https://ragr3n.github.io
nav:
  - Home: index.md
  - Homelab: homelab_2024.md
  - Command Cheat Sheet: cheat_sheet.md
  - Links: links.md
theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
